[package]
name = "helgoboss-learn"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
helgoboss-midi = { version = "0.1.0", path = '../helgoboss-midi-rs' }
num = "0.2.1"
num_enum = "0.5.0"

approx = "0.3.2"
derive_more = "0.99.5"
enum-iterator = "0.6.0"